kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: anjanaz/python-tier:latest
        ports:
        - containerPort: 5050

---
kind: Service
apiVersion: v1 
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  type: ClusterIP

    